### ISSUE TITLE
Couple thoughts...

### ISSUE THREAD

**Issue by tracker1** [gaui/todoApp-angular-mobx-webpack#1]
Nice structure, better than most ng apps I've seen...
- would throw `babel-loader` in the mix with `es2015` and `stage-1` (or 2).
- Controllers are constructor functions, `PascalCase`
  - with babel in place, I'd probably use the ES2015 class syntax for controllers.
- Add unit linting and unit testing... personally, I like `.(test|spec).js` unit test files next to what's being tested, but that's only me.

**Comment by gaui** [comment]
Thank you but it was my intention to write this in ES5 and not ES2015. Majority of Angular 1.x today applications are written in ES5 and that's why I decided to stick to ES5. If I decide to rewrite this using ES2015, I will create another repo.
